name: Save Logs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download logs to file
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifact

      - name: 顯示檔案結構 - 測試
        run: ls -R
        working-directory: docs/assets/images/bot
